flamengo = [
    "3' - Início do primeiro tempo.",
    "3' - Escanteio, Flamengo. Cedido por Breno Lopes.",
    "6' - Josué (Coritiba) sofre uma falta no campo defensivo.",
    "6' - Falta cometida por Bruno Henrique (Flamengo).",
    "6' - Breno Lopes (Coritiba) sofre uma falta no campo defensivo.",
    "6' - Falta cometida por Emerson Royal (Flamengo).",
    "8' - Oportunidade perdida João Pedro Chermont (Coritiba), de cabeça do meio da área.",
    "8' - Oportunidade perdida Sebastián Gómez (Coritiba), de cabeça de um ângulo dificil da esquerda. Assistência de João Pedro Chermont.",
    "10' - Oportunidade perdida Jacy (Coritiba), finalização com o pé direito de fora da área.",
    "11' - GOOOOOOOOL! Gol! Flamengo 1, Coritiba 0. Samuel Lino (Flamengo) finalização com o pé direito de fora da área.",
    "13' - Oportunidade perdida Luiz Araújo (Flamengo), finalização com o pé esquerdo de fora da área. Assistência de Emerson Royal.",
    "16' - Escanteio, Coritiba. Cedido por Ayrton Lucas.",
    "17' - Oportunidade perdida Sebastián Gómez (Coritiba), finalização com o pé esquerdo do lado esquerdo da área após escanteio.",
    "18' - Partida interrompida devido a uma lesão de Léo Ortiz (Flamengo).",
    "19' - Partida recomeça.",
    "19' - Substituição Flamengo, entra em campo João Victor substituindo Léo Ortiz uma lesão.",
    "19' - Josué (Coritiba) sofre uma falta no campo adversário.",
    "19' - Falta cometida por Bruno Henrique (Flamengo).",
    "20' - Oportunidade perdida Ayrton Lucas (Flamengo), finalização com o pé esquerdo de fora da área.",
    "21' - Finalização defendida junto ao lado inferior direito do gol. Pedro (Flamengo) finalização com o pé direito de fora da área. Assistência de Luiz Araújo.",
    "24' - Finalização defendida. Samuel Lino (Flamengo) finalização com o pé esquerdo do lado esquerdo da área.",
    "25' - Finalização defendida em direção ao centro do gol. Pedro (Flamengo) finalização com o pé direito do lado esquerdo da área.",
    "25' - Finalização bloqueada, Bruno Henrique (Flamengo) finalização com o pé esquerdo de fora da área.",
    "26' - Finalização defendida em direção ao centro do gol. Luiz Araújo (Flamengo) finalização com o pé esquerdo de fora da área. Assistência de Pedro.",
    "27' - Escanteio, Flamengo. Cedido por Tiago Cóser.",
    "28' - Partida interrompida devido a uma lesão de Thiago Santos (Coritiba).",
    "29' - Partida recomeça.",
    "31' - Falta cometida por Pedro Rocha (Coritiba).",
    "31' - Vitão (Flamengo) sofre uma falta no campo defensivo.",
    "32' - Partida interrompida devido a uma lesão de Vitão (Flamengo).",
    "33' - Pedro Rocha (Coritiba) recebe cartão amarelo por uma entrada perigosa.",
    "34' - Conferindo o VAR: Possível Cartão Vermelho.",
    "34' - Partida interrompida devido a de (Coritiba). Revisão por vídeo.",
    "36' - Partida recomeça.",
    "36' - Pedro Rocha (Coritiba) recebe cartão vermelho.",
    "37' - Escanteio, Flamengo. Cedido por João Pedro Chermont.",
    "38' - Thiago Santos (Coritiba) sofre uma falta no campo defensivo.",
    "38' - Falta cometida por Luiz Araújo (Flamengo).",
    "41' - João Pedro Chermont (Coritiba) sofre uma falta na lateral direita.",
    "41' - Falta cometida por Erick Pulgar (Flamengo).",
    "41' - Erick Pulgar (Flamengo) recebe cartão amarelo por uma entrada perigosa.",
    "42' - Oportunidade perdida Jacy (Coritiba), de cabeça do lado esquerdo da área.",
    "43' - Falta cometida por Tiago Cóser (Coritiba).",
    "43' - Bruno Henrique (Flamengo) sofre uma falta no campo adversário.",
    "45' - Escanteio, Flamengo. Cedido por Tiago Cóser.",
    "45' - Oportunidade perdida Pedro (Flamengo), finalização com o pé direito do meio da área.",
    "45' - O quarto árbitro anunciou 6 minutos de acréscimo.",
    "48' - Escanteio, Flamengo. Cedido por Josué.",
    "48' - Oportunidade perdida Bruno Henrique (Flamengo), finalização com o pé esquerdo do meio da área após escanteio.",
    "51' - Finalização defendida. Emerson Royal (Flamengo) finalização com o pé direito de fora da área.",
    "51' - Oportunidade perdida Erick Pulgar (Flamengo), finalização com o pé direito de fora da área. Assistência de Pedro com um passe de cabeça.",
    "52' - Fim do primeiro tempo, Flamengo 1, Coritiba 0."
]
# fonte = https://www.terra.com.br/esportes/futebol/brasileiro-serie-a/ao-vivo/flamengo-x-coritiba/95617/

champions_league = [
    "1' - Início do primeiro tempo.",
    "1' - Falta cometida por Achraf Hakimi (Paris Saint-Germain).",
    "1' - Leandro Trossard (Arsenal) sofre uma falta na lateral esquerda.",
    "5' - Bukayo Saka (Arsenal) sofre uma falta no campo defensivo.",
    "5' - Falta cometida por Fabián Ruiz (Paris Saint-Germain).",
    "6' - GOOOOOOOOL! Gol! Paris Saint-Germain 0, Arsenal 1. Kai Havertz (Arsenal) finalização com o pé esquerdo de um ângulo dificil da esquerda.",
    "7' - Myles Lewis-Skelly (Arsenal) sofre uma falta no campo defensivo.",
    "7' - Falta cometida por Vitinha (Paris Saint-Germain).",
    "9' - Falta cometida por Bukayo Saka (Arsenal).",
    "9' - Ousmane Dembélé (Paris Saint-Germain) sofre uma falta na lateral esquerda.",
    "10' - Impedimento, Arsenal. William Saliba tentou um passe em profundidade que encontrou Kai Havertz in posição irregular.",
    "11' - Escanteio, Paris Saint-Germain. Cedido por Gabriel Magalhães.",
    "13' - Oportunidade perdida Fabián Ruiz (Paris Saint-Germain), finalização com o pé esquerdo do lado esquerdo da área. Assistência de Désiré Doué com um passe em profundidade.",
    "14' - Falta cometida por Bukayo Saka (Arsenal).",
    "14' - Nuno Mendes (Paris Saint-Germain) sofre uma falta no campo defensivo.",
    "14' - Kai Havertz comemora gol do Arsenal",
    "15' - Falta cometida por Myles Lewis-Skelly (Arsenal).",
    "15' - João Neves (Paris Saint-Germain) sofre uma falta no campo defensivo.",
    "16' - Escanteio, Paris Saint-Germain. Cedido por Piero Hincapié.",
    "23' - Partida interrompida devido a pausa para hidratação de.",
    "25' - Partida recomeça.",
    "26' - Partida interrompida devido a uma lesão de Matvey Safonov (Paris Saint-Germain).",
    "29' - Partida recomeça.",
    "34' - Escanteio, Paris Saint-Germain. Cedido por Piero Hincapié.",
    "36' - Bukayo Saka (Arsenal) sofre uma falta na lateral direita.",
    "36' - Falta cometida por Nuno Mendes (Paris Saint-Germain).",
    "37' - Falta cometida por Kai Havertz (Arsenal).",
    "37' - Fabián Ruiz (Paris Saint-Germain) sofre uma falta no campo defensivo.",
    "37' - Finalização bloqueada, Ousmane Dembélé (Paris Saint-Germain) finalização com o pé esquerdo do lado direito da área. Assistência de Vitinha.",
    "43' - Oportunidade perdida Fabián Ruiz (Paris Saint-Germain), de cabeça do meio da área.",
    "45' - Oportunidade perdida Ousmane Dembélé (Paris Saint-Germain), finalização com o pé esquerdo de fora da área.",
    "45' - O quarto árbitro anunciou 6 minutos de acréscimo.",
    "47' - Oportunidade perdida Désiré Doué (Paris Saint-Germain), finalização com o pé esquerdo de fora da área.",
    "48' - Finalização bloqueada, Kai Havertz (Arsenal) finalização com o pé esquerdo do lado direito da área. Assistência de Martin Ødegaard com um passe em profundidade.",
    "49' - Escanteio, Paris Saint-Germain. Cedido por Leandro Trossard.",
    "50' - Finalização defendida em direção ao centro do gol. Fabián Ruiz (Paris Saint-Germain) finalização com o pé esquerdo de um ângulo difícil e passa um pouco longe à esquerda. Assistência de Vitinha.",
    "51' - Escanteio, Arsenal. Cedido por Willian Pacho.",
    "51' - Finalização bloqueada, Kai Havertz (Arsenal) de cabeça do lado direito da pequena área. Assistência de Declan Rice.",
    "52' - Fim do primeiro tempo, Paris Saint-Germain 0, Arsenal 1."
]

# fonte = https://www.terra.com.br/esportes/futebol/internacional/liga-dos-campeoes/ao-vivo/paris-saint-germain-x-arsenal/95615/